# Generated by Django 4.2.18 on 2025-02-04 13:05

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=student.models.create_directory)),
                ('checkbox', models.BooleanField(blank=True)),
            ],
        ),
    ]
